### ISSUE TITLE
Vulnerable Components used: org.bouncycastle:bcpkix-jdk15on:1.54 / 1.58

### ISSUE THREAD

**Issue by st-keller** [adorsys/secure-token-service#11]
Please update org.bouncycastle:bcpkix-jdk15on:1.54 (dependency of cryptoutils). 
**Version 1.54 has a known vulnerability!**
A newer Version (1.6) without known vulnerabilities is present!

**Comment by st-keller** [comment]
+- de.adorsys:docusafe-service:jar:0.5.8:compile
|  +- org.bouncycastle:bcprov-jdk15on:jar:1.60:compile
|  \- **org.bouncycastle:bcpkix-jdk15on:jar:1.54:compile**


+- de.adorsys.cryptoutils:jjwk:jar:0.23.5:compile
|  +- commons-io:commons-io:jar:2.5:compile
|  \- de.adorsys.cryptoutils:jkeyutils:jar:0.23.5:compile
|     +- **org.bouncycastle:bcpkix-jdk15on:jar:1.58:compile**
|     |  \- org.bouncycastle:bcprov-jdk15on:jar:1.60:compile

**Comment by borisskert** [comment]
Will be fixed with pull request #13
