### ISSUE TITLE
SecurityConfiguration problem

### ISSUE THREAD

**Issue by holgervelke** [adorsys/secure-token-service#163]
`de.adorsys.sts:sts-secret-server:1.1.3` has a SecurityConfiguration error:

`java.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins cannot contain the special value "*" since that cannot be set on the "Access-Control-Allow-Origin" response header. To allow credentials to a set of origins, list them explicitly or consider using "allowedOriginPatterns" instead.
`

**Comment by Mme-adorsys** [comment]
Made cors policy configurable over properties to set allowedOrigins

cors:
  allowedOrigins: http://localhost:3000/,http://example.com/
  allowedHeaders: "*"
  allowedMethods: GET,POST,PUT,DELETE
