### ISSUE TITLE
No claims in token

### ISSUE THREAD

**Issue by max402** [adorsys/secure-token-service#96]
> Hello!

we implement the new STS Client Version 1.0.1 with the extended logging. It looks like the logging is working but every request raise an error message "Token has no claims" but the applications still works and finish the request without an error from user side. 

It looks like claims are not required for a token. 

https://github.com/adorsys/secure-token-service/blob/c659467894e78b8468ca3dec8bf8a1f731bb9793/sts-token-auth/src/main/java/de/adorsys/sts/tokenauth/BearerTokenValidator.java#L42

**Comment by francis-pouatcha** [comment]
Check with @max402 if ticket still relevant. Eventually have him elaborate on the Ticket.
